FROM node:16-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
RUN npm install

#RUN npm run build

# Bundle app source
COPY . .

# Exports
EXPOSE 3000
#CMD [ "npm", "run", "dev" ]
CMD [ "node", "./build/index.js"]