version: "3.5"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:3000"
    depends_on:
      - app-express

  keyrock:
    image: fiware/idm:7.8.1
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - mysql-db
    ports:
      - "5001:5001"
      - "443:443"
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://localhost:5001
      - IDM_PORT=5001
      # Development use only
      # Use Docker Secrets for Sensitive Data
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234
      # # If sending eMails point to any STMP server
      # - IDM_EMAIL_HOST=mailer
      # - IDM_EMAIL_PORT=25

  mysql-db:
    restart: always
    image: mysql:5.7
    hostname: mysql-db
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      # Development use only
      # Use Docker Secrets for Sensitive Data
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=172.18.1.5"
    volumes:
      - mysql-db:/var/lib/mysql

  # Configure the SMTP settings below as necessary,
  # For example to use Gmail SMTP
  #
  # server address: smtp.gmail.com
  # username: Your Gmail address (for example, example@gmail.com)
  # password: Your Gmail password
  # port (TLS): 587
  # port (SSL): 465
  # TLS/SSL required: Yes

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

  mongo:
    image: mongo:4.4
    command: --nojournal

  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    # network_mode: "host"
    command: -dbhost mongo

  app-express:
    build:
      context: ./app-express
      dockerfile: Dockerfile.dev
    volumes:
      - ./app-express:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    depends_on:
      - orion
      - mongodb
      - keyrock
      - mysql-db
    ports:
      - "5000:5000"

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mongodb:
  mongodb_config:
  mysql-db: ~
