### Create super admin token
POST http://localhost:5001/v1/auth/tokens
Content-Type: application/json

{
  "name":"admin@test.com",
  "password": "1234"
}

### Get user's access token
POST http://localhost:5001/oauth2/token
Host: account.lab.fiware.org
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YjEyYzljYWMtNGJjYi00MmM0LWJhYzgtZjllNjBmYTRiZjE3OjY5YTZlNTcxLWMzM2EtNDY2NC04MmJhLWRmMDFmNzU3NjM5NQ==

grant_type=password&username=theo@test.com&password=test

### Get data from access_token
GET http://localhost:5001/user?access_token=9b603691fe9ae21352d1cacf1af289493efbc4e2

### Get all roles and role ids
GET http://localhost:5001/v1/applications/5181153a-170f-4ad4-a810-08709eee604f/roles 
Content-Type: application/json
X-Auth-token: 4ac170a9-065a-4141-ac34-3235238900f5

### Grant a role to the user
POST http://localhost:5001/v1/applications/b12c9cac-4bcb-42c4-bac8-f9e60fa4bf17/users/cac933dc-8a9e-4ba6-ade7-5e7b73f1afb2/roles/164dbd75-ecb4-4528-94e9-4de64d5cf06b
Content-Type: application/json
X-Auth-token: 943038ed-19a9-4a72-8f5b-43ae9b0966d8

### Revoke a role from the user
DELETE http://localhost:5001/v1/applications/b12c9cac-4bcb-42c4-bac8-f9e60fa4bf17/users/cac933dc-8a9e-4ba6-ade7-5e7b73f1afb2/roles/164dbd75-ecb4-4528-94e9-4de64d5cf06b
Content-Type: application/json
X-Auth-token: 943038ed-19a9-4a72-8f5b-43ae9b0966d8