###create a user
POST http://localhost:5000/auth/create-user
Content-Type: application/json

{"name":"name123","surname":"surname123","username":"username123","email":"email1@gmail.com","password":"password123"}

###create a user
POST http://localhost:5000/auth/create-user
Content-Type: application/json

{"name":"name123","surname":"surname123","username":"username123","email":"email222@gmail.com","password":"password123"}

###create a user
POST http://localhost:5000/auth/create-user
Content-Type: application/json

{"name":"name123","surname":"surname123","username":"username123","email":"email4@gmail.com","password":"password123"}

###login a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{"email":"email1@gmail.com","password":"password123"}

###get user data
POST http://localhost:5000/auth/user-data
Content-Type: application/json

{"access_token":"3a1273ff949dd6bc3d42b37e0ff27a3114c9ae2c","refresh_token":"nannananann"}